name: general-tests
on: [push]
jobs:
  cppcheck:
    name: Shell static check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cppcheck
        uses: deep5050/cppcheck-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          std: c99, c++11

      - name: Publish cppcheck results
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'