name: general-tests
on: [push]
jobs:
  cppcheck:
    name: Shell static check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          std: c99, c++11