name: general-tests
on: [push]
jobs:
  cppcheck:
    name: Shell static check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          depth: 1
          submodules: 'recursive'

      - name: Run Cppcheck
        uses: Bedzior/cppcheck-action@v2.0.0
        with:
          enabled checks: all
          enable inconclusive: true
          path: ./src