name: wordcount-tests
on: [push]
jobs:
  io-unit:
    name: Unit tests for io module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build program modules binaries
        run: cd src ; make ; cd ..

      - name: Build test binaries
        run: cd test ; make ; cd ..

      - name: Run tests
        run: ./test/io-unit.sh 2> /dev/null
